ktor {
    deployment {
        port = 8080
    }

    application {
        modules = [ com.example.simplifymypantry.ApplicationKt.module ]
    }
}
#UNCOMMENT THIS AND COMMENT H2 FOR PRODUCTION
#database {
#    url = "jdbc:postgresql://localhost:5432/userdb"
#    driver = "org.postgresql.Driver"
#    user = "postgres"
#    password = "password"
#}

database {
    url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driver = "org.h2.Driver"
    user = "user"
    password = "pass"
}

jwt {
    secret = "secretString"
    }